### ISSUE TITLE
是否有執行教學?

### ISSUE THREAD

**Issue by bnm890** [hirohe/facerec-python#1]
你好,看到你的項目,想要學習一下,
但只看到運行要求
安裝要求都沒有出現
能提供嗎?

**Comment by hirohe** [comment]
以前的树莓派坏了，最近刚买了一块
我找时间整理一下吧

**Comment by bnm890** [comment]
好的．因為最近買了3代，一直無法測試成功!!

**Comment by hirohe** [comment]
@bnm890 整理好了，请试一下

**Comment by bnm890** [comment]
@hirohe 感謝您!! 最近有空檔時會再來玩

**Comment by bnm890** [comment]
你好,我測試後 點選其中一個都只有出現白畫面
http://imgur.com/a/vkIAo

我操作流程
sudo apt-get update
↓
sudo apt-get install build-essential cmake pkg-config python-dev libgtk2.0-dev libgtk2.0 zlib1g-dev libpng-dev libjpeg-dev libtiff-dev libjasper-dev libavcodec-dev swig unzip
↓
sudo wget https://jaist.dl.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.9/opencv-2.4.9.zip
↓
unzip opencv-2.4.9.zip
↓
cd opencv-2.4.9
↓
sudo cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_PERF_TESTS=OFF -DBUILD_opencv_gpu=OFF -DBUILD_opencv_ocl=OFF
↓
make -j4
↓
sudo make install
↓
sudo apt-get install python-qt4
↓
sudo nano /etc/modules
  //增加一行记录
  bcm2835-v4l2
 // 重启后可以找到/dev/video0
↓
sudo apt-get install autoconf gettext libtool libjpeg8 libjpeg8-dev
↓
git clone git://git.linuxtv.org/v4l-utils.git
↓  
cd v4l-utils
↓
sudo ./bootstrap.sh
↓
sudo ./configure
↓
make -j4
↓
sudo make install
↓
python main.py

**Comment by hirohe** [comment]
嘗試用ssh連接並項目目錄下運行DISPLAY=:0.0 python main.py
以此查看輸出信息

**Comment by hirohe** [comment]
@bnm890 看來你是在編譯opencv之前沒有開啟對v4l的支持，先開啟v4l2驅動再重新編譯並安裝opencv
確保在opencv源碼目錄下運行cmake之後有如下輸出
```bash
V4L/V4L2:                    Using libv4l (ver 1.13.0)
```

**Comment by bnm890** [comment]
請問這一段
V4L/V4L2:                    Using libv4l (ver 1.13.0)
是會在ssh編譯完出現嗎?
http://imgur.com/a/w1qnJ
還是要去特定資料夾某個文件打開查看呢?

**Comment by hirohe** [comment]
是的，查看命令行输出，往上翻...

**Comment by bnm890** [comment]
剛剛照你的流程跑完後再pi 上面執行會出現
not found cv2 module
是用python 2.7.x 按F5執行

**Comment by bnm890** [comment]
另外請問step2 编译OpenCV 2.4.9
http://imgur.com/a/3MT3D

是在 v4l-utils/ 下執行?
還是要"cd" 回主目錄執行?

**Comment by hirohe** [comment]
1.not found cv2 module 说明你没有编译安装好opencv
2.编译opencv当然是在opencv的源码文件夹下进行

**Comment by bnm890** [comment]
請問可以加QQ或是微信嗎?

**Comment by hirohe** [comment]
需要讨论的话还是到[https://gitter.im/hirohe/facerec-python](https://gitter.im/hirohe/facerec-python)来吧
