### ISSUE TITLE
怎么使用？

### ISSUE THREAD

**Issue by SaltNego** [hirohe/facerec-python#3]
求教

**Comment by hirohe** [comment]
- 一块运行raspberry Jessise的树莓派2或3
- 树莓派摄像头模块

按照[README](https://github.com/hirohe/facerec-python/blob/master/README.md)的指引搭建环境
搭建过程有问题可以问一下我

**Comment by SaltNego** [comment]
3Q,这个项目的作用是什么

**Comment by hirohe** [comment]
人脸识别的练习

**Comment by bnm890** [comment]
樹莓派3 使用上沒有問題
第一次使用記得屏幕要轉,不然會看不到控件
