### ISSUE TITLE
關於修改畫面問題

### ISSUE THREAD

**Issue by bnm890** [hirohe/facerec-python#4]
你好,練習修改畫面成800*480
有幾個問題想問
Q1.
http://imgur.com/a/PcJuH
這個輸入使用者的小視窗我始終找不到(setGeometry)來設定他的X Y 座標
Q2.
http://imgur.com/a/C4BKf
人臉登入發現他們偵測人臉後所顯示的框框並沒有在人臉上而是在旁邊顯示方框
有發現到如果要把方框畫在臉上必須要先執行第1個 人臉辨識，人臉登入才會把方框畫在人臉上

**Comment by hirohe** [comment]
- Q1: 我使用輸入使用者的小視窗可以考虑不使用小視窗，改到人脸录入窗口。并且使用软键盘是为了适用于触摸屏
- Q2: 方框错位我也遇到过，我找时间去重现一下看看问题吧

**Comment by bnm890** [comment]
Q1. 我的是触摸屏會使用到這個小視窗,只是想問是哪段程式決定它顯示的位置?

Q2.
你有時間的時候可以試看看我的實驗方法
***************
Step1. 一開啟程式直接選擇人臉登入
Step2. 偵測到人臉方框就會出現在其他地方,不會在人臉上
**************
Step1. 一開啟程式先做人臉辨識
Step2. 返回主頁面 選擇人臉登入
Step3. 登入人臉偵測到人臉的方框就正常

覺得應該是人臉登入用的參數有用到人臉偵測,這幾天有空我也在研究看看哪邊的參數影響到

**Comment by hirohe** [comment]
@bnm890 人臉登入中导致方框错位的问题是分辨率设置的问题
在video初始化时设置了分辨率为1280x720
```python
video.setFrameSize(1280, 720)
```
[这里](https://github.com/hirohe/facerec-python/commit/278996ef7d7d20bab0dfe40c65cd8b955bfa4ec8#diff-5bc02cefb3ea9e27f1a6776eabd1935dL17)

不过暂时没看到什么导致分别进入人脸识别和人脸录入时，摄像头的分辨率不同，我之后仔细看看

**Comment by bnm890** [comment]
我的屏幕是800X480 的橫屏觸控屏
這裡我就改成800X480可以解決?

**Comment by hirohe** [comment]
`video.setFrameSize(640, 480)`

**Comment by bnm890** [comment]
成功了!!
我之前都找錯方向
難怪一直試不成功
感謝
