### ISSUE TITLE
開機自啟無法正常動作

### ISSUE THREAD

**Issue by bnm890** [hirohe/facerec-python#5]
你好,我想使用開機自啟功能
http://www.jianshu.com/p/1a160067d8fd
以上網址的3種方法 都失敗

請問是此程式無法自啟?!

**Comment by hirohe** [comment]
请问你的问题解决了吗？
我用的方法是在/etc/rc.local增加运行这个项目的命令

**Comment by bnm890** [comment]
目前新增完沒有效果
http://imgur.com/a/rGiau

**Comment by hirohe** [comment]
我自己试了一下
在/etc/rc.local设置的方法，在新的树莓派系统下不能直接使用了
而我之前是在旧的系统上使用开机自启的，我之后去找找其他方法看看
或许这个能帮助你[How to Enable /etc/rc.local with Systemd](https://www.linuxbabe.com/linux-server/how-to-enable-etcrc-local-with-systemd)

**Comment by bnm890** [comment]
好的!!我試看看~
